version: 0.2
env:
  variables:
    CDK_SRC_DIR: tulsa-weather-app/cdk
    APP_SRC_DIR: tulsa-weather-app/react-app
  parameter-store:
    API_URL: /tulsa-weather-api/api-url
phases:
  install:
    runtime_versions:
      nodejs: 12
    commands:
     - cd ${CODEBUILD_SRC_DIR}/${CDK_SRC_DIR}
     - npm install
     - cd ${CODEBUILD_SRC_DIR}/${APP_SRC_DIR}
     - npm install
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/${APP_SRC_DIR}
      - REACT_APP_OWM_API_URL=${API_URL} npm run build
      - cd ${CODEBUILD_SRC_DIR}/${CDK_SRC_DIR}
      - npm run cdk deploy -- --require-approval never