  
version: 0.2

phases:

  install:
    runtime_versions:
      nodejs: 12
    commands:
     - cd ${CODEBUILD_SRC_DIR}/tulsa-weather-backend
     - npm install

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/tulsa-weather-api
      - npm install
      - npm run build
      - npm run deploy
