  
version: 0.2

phases:

  install:
    runtime_versions:
      nodejs: 12
    commands:
     - cd ${CODEBUILD_SRC_DIR}/tulsa-weather-backend
     - npm install

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/tulsa-weather-api
      - npm install
      - npm run build
      - cd ../tulsa-weather-backend
      - npm run cdk deploy LambdaDeployment --require-approval never --outputs-file ../tulsa-weather-app/src/apiConfig.json
      - cd ../tulsa-weather-app
      - npm run build
      - cd ../tulsa-weather-backend
      - cdk deploy ReactDeployment --require-approval never
